### ISSUE TITLE
NullPointerException when saving entity

### ISSUE THREAD

**Issue by Niko-sk2x** [Foghrye4/Labyrinth#1]
```
[06:04:18] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.writeToNBT(Entity.java:1939) ~[Entity.class:?]
	at net.minecraft.entity.Entity.writeToNBTOptional(Entity.java:1822) ~[Entity.class:?]
	at cubicchunks.world.EntityContainer.writeToNbt(EntityContainer.java:163) ~[EntityContainer.class:?]
	at cubicchunks.server.chunkio.IONbtWriter.writeEntities(IONbtWriter.java:157) ~[IONbtWriter.class:?]
	at cubicchunks.server.chunkio.IONbtWriter.write(IONbtWriter.java:90) ~[IONbtWriter.class:?]
	at cubicchunks.server.chunkio.RegionCubeIO.saveCube(RegionCubeIO.java:159) ~[RegionCubeIO.class:?]
	at cubicchunks.server.CubeProviderServer.saveChunks(CubeProviderServer.java:163) ~[CubeProviderServer.class:?]
	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1073) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:426) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:238) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:722) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at labyrinth.entity.EntitySlimeLeveled.writeEntityToNBT(EntitySlimeLeveled.java:51) ~[EntitySlimeLeveled.class:?]
	at net.minecraft.entity.Entity.writeToNBT(Entity.java:1910) ~[Entity.class:?]
	... 13 more
```

I got this exception when flying straight down in spectator mode for long enough. I was running it in dev environment because I was testing if my changes didn't break this mod.

**Comment by Foghrye4** [comment]
Should be fine now.
